import { App, ItemView, Modal, Notice, Plugin, PluginSettingTab, Setting, TFile, WorkspaceLeaf, normalizePath, requestUrl } from "obsidian";

type MediaType = "movie" | "series";
type FamilyDecision = "approved" | "use-discernment" | "not-for-us" | "not-reviewed";
type ConcernLevel = "none" | "mild" | "moderate" | "severe" | "not-reviewed";
type GalleryDensity = "compact" | "comfortable" | "large";
type FamilyGuide = { decision: FamilyDecision; minAge: string; violence: ConcernLevel; sexualContent: ConcernLevel; language: ConcernLevel; substances: ConcernLevel; themes: ConcernLevel; notes: string; prompts: string };
type MediaRecord = { id: string; title: string; mediaType: MediaType; year: string; runtime: number | null; genres: string[]; director: string; cast: string[]; imdbId: string; contentRating: string; plot: string; posterUrl: string; plexThumbPath: string; plexRatingKey: string; lists: string[]; watched: boolean; watchlist: boolean; owned: boolean; favorite: boolean; personalRating: number | null; lastWatched: string; created: string; updated: string; family: FamilyGuide; path: string };
type OmdbResult = { Title?: string; Year?: string; imdbID?: string; Type?: string; Poster?: string; Runtime?: string; Genre?: string; Director?: string; Actors?: string; Rated?: string; Plot?: string; Response?: string; Error?: string };
type SettingsData = { rootFolder: string; omdbKey: string; plexServerUrl: string; plexToken: string; plexLibraryKeys: string[]; galleryDensity: GalleryDensity; pickerWatchlistFirst: boolean; defaultFamilyDecision: FamilyDecision; defaultMinAge: string };
type PlexLibrary = { key: string; title: string; type: string };
type PlexMetadata = { ratingKey?: string | number; title?: string; type?: string; year?: string | number; duration?: number; Genre?: Array<{ tag?: string }>; Director?: Array<{ tag?: string }>; Role?: Array<{ tag?: string }>; Guid?: Array<{ id?: string }>; contentRating?: string; summary?: string; thumb?: string; viewCount?: string | number; lastViewedAt?: string | number; userRating?: string | number };

const VIEW = "movie-library-dashboard";
const INDEX_START = "<!-- movie-library:index:start -->";
const INDEX_END = "<!-- movie-library:index:end -->";
const DETAIL_START = "<!-- movie-library:details:start -->";
const DETAIL_END = "<!-- movie-library:details:end -->";
const FAMILY_DECISIONS: Record<FamilyDecision, string> = { approved: "Approved", "use-discernment": "Use discernment", "not-for-us": "Not for us", "not-reviewed": "Not reviewed" };
const CONCERN_LEVELS: Record<ConcernLevel, string> = { none: "None", mild: "Mild", moderate: "Moderate", severe: "Severe", "not-reviewed": "Not reviewed" };
const DEFAULT: SettingsData = { rootFolder: "Movie Library", omdbKey: "", plexServerUrl: "", plexToken: "", plexLibraryKeys: [], galleryDensity: "comfortable", pickerWatchlistFirst: true, defaultFamilyDecision: "not-reviewed", defaultMinAge: "" };
const LIST_TAG_PREFIX = "movie-library/list/";

const dateToday = (): string => new Date().toISOString().slice(0, 10);
const now = (): string => new Date().toISOString().slice(0, 16);
const id = (): string => `MED-${Math.random().toString(36).slice(2, 6).toUpperCase()}${Date.now().toString(36).slice(-4).toUpperCase()}`;
const normalize = (value: string): string => value.trim().replace(/\s+/g, " ").toLocaleLowerCase();
const safe = (value: string): string => value.trim().replace(/[\\/:*?"<>|#[\]]/g, "-").replace(/\s+/g, " ").slice(0, 76) || "Untitled";
const list = (value: unknown): string[] => Array.isArray(value) ? value.map(String).map(v => v.replace(/^\[\[|\]\]$/g, "").trim()).filter(Boolean) : typeof value === "string" && value.trim() ? value.split(",").map(v => v.trim()).filter(Boolean) : [];
const bool = (value: unknown): boolean => value === true || String(value).toLocaleLowerCase() === "true";
const number = (value: unknown): number | null => { const result = Number(value); return Number.isFinite(result) && result > 0 ? result : null; };
const typeOf = (value: unknown): MediaType => String(value).toLocaleLowerCase() === "series" ? "series" : "movie";
const decisionOf = (value: unknown): FamilyDecision => typeof value === "string" && Object.prototype.hasOwnProperty.call(FAMILY_DECISIONS, value) ? value as FamilyDecision : "not-reviewed";
const concernOf = (value: unknown): ConcernLevel => typeof value === "string" && Object.prototype.hasOwnProperty.call(CONCERN_LEVELS, value) ? value as ConcernLevel : "not-reviewed";
const parseRuntime = (value: string): number | null => { const match = value.match(/\d+/); return match ? number(match[0]) : null; };
const defaultFamily = (settings: SettingsData): FamilyGuide => ({ decision: settings.defaultFamilyDecision, minAge: settings.defaultMinAge, violence: "not-reviewed", sexualContent: "not-reviewed", language: "not-reviewed", substances: "not-reviewed", themes: "not-reviewed", notes: "", prompts: "" });
const unique = (values: string[]): string[] => [...new Map(values.map(value => [normalize(value), value.trim()])).values()].filter(Boolean);
const listTag = (name: string): string => `${LIST_TAG_PREFIX}${name.trim().toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu, "-").replace(/^-|-$/g, "")}`;
const listLabel = (tag: string): string => tag.slice(LIST_TAG_PREFIX.length).split("-").filter(Boolean).map(word => word.slice(0, 1).toLocaleUpperCase() + word.slice(1)).join(" ");

class MovieRepository {
  constructor(private app: App, private settings: SettingsData) {}
  get root(): string { return normalizePath(this.settings.rootFolder.trim().replace(/^\/+|\/+$/g, "") || DEFAULT.rootFolder); }
  get mediaRoot(): string { return normalizePath(`${this.root}/Media`); }
  configure(settings: SettingsData): void { this.settings = settings; }
  async initialize(): Promise<void> { for (const path of [this.root, this.mediaRoot]) if (!this.app.vault.getAbstractFileByPath(path)) await this.app.vault.createFolder(path); }
  private frontmatter(file: TFile): Record<string, unknown> { return (this.app.metadataCache.getFileCache(file)?.frontmatter ?? {}) as Record<string, unknown>; }
  records(): MediaRecord[] { return this.app.vault.getMarkdownFiles().filter(file => file.path.startsWith(`${this.mediaRoot}/`)).map(file => this.fromFile(file)).filter((record): record is MediaRecord => Boolean(record)).sort((a, b) => b.created.localeCompare(a.created)); }
  private fromFile(file: TFile): MediaRecord | null { const fm = this.frontmatter(file); if (fm.type !== "movie-library-media") return null; const familyValue = fm.family && typeof fm.family === "object" ? fm.family as Record<string, unknown> : {}; return { id: String(fm.media_id ?? ""), title: String(fm.title ?? file.basename), mediaType: typeOf(fm.media_type), year: String(fm.year ?? ""), runtime: number(fm.runtime_minutes), genres: list(fm.genres), director: String(fm.director ?? ""), cast: list(fm.cast), imdbId: String(fm.imdb_id ?? ""), contentRating: String(fm.content_rating ?? ""), plot: String(fm.plot ?? ""), posterUrl: String(fm.poster_url ?? ""), plexThumbPath: String(fm.plex_thumb_path ?? ""), plexRatingKey: String(fm.plex_rating_key ?? ""), lists: unique(list(fm.tags).filter(tag => tag.toLocaleLowerCase().startsWith(LIST_TAG_PREFIX)).map(tag => listLabel(tag))), watched: bool(fm.watched), watchlist: bool(fm.watchlist), owned: bool(fm.owned), favorite: bool(fm.favorite), personalRating: number(fm.personal_rating), lastWatched: String(fm.last_watched ?? ""), created: String(fm.created ?? ""), updated: String(fm.updated ?? ""), family: { decision: decisionOf(familyValue.decision), minAge: String(familyValue.min_age ?? ""), violence: concernOf(familyValue.violence), sexualContent: concernOf(familyValue.sexual_content), language: concernOf(familyValue.language), substances: concernOf(familyValue.substances), themes: concernOf(familyValue.themes), notes: String(familyValue.notes ?? ""), prompts: String(familyValue.prompts ?? "") }, path: file.path }; }
  private duplicate(input: MediaRecord, skipPath = ""): MediaRecord | undefined { const titleKey = normalize(input.title); return this.records().find(record => record.path !== skipPath && ((input.imdbId && record.imdbId === input.imdbId) || (normalize(record.title) === titleKey && record.year === input.year && record.mediaType === input.mediaType))); }
  private personalNotes(content: string): string { const marker = "## Personal notes"; const at = content.indexOf(marker); return at >= 0 ? content.slice(at + marker.length).trim() : ""; }
  private render(record: MediaRecord, personalNotes: string): string { const family = record.family; const yaml = ["---", "type: movie-library-media", `media_id: ${JSON.stringify(record.id)}`, `title: ${JSON.stringify(record.title)}`, `media_type: ${record.mediaType}`, `year: ${JSON.stringify(record.year)}`, `runtime_minutes: ${record.runtime ?? ""}`, `genres: ${JSON.stringify(record.genres)}`, `director: ${JSON.stringify(record.director)}`, `cast: ${JSON.stringify(record.cast)}`, `imdb_id: ${JSON.stringify(record.imdbId)}`, `content_rating: ${JSON.stringify(record.contentRating)}`, `plot: ${JSON.stringify(record.plot)}`, `poster_url: ${JSON.stringify(record.posterUrl)}`, `plex_thumb_path: ${JSON.stringify(record.plexThumbPath)}`, `plex_rating_key: ${JSON.stringify(record.plexRatingKey)}`, `watched: ${record.watched}`, `watchlist: ${record.watchlist}`, `owned: ${record.owned}`, `favorite: ${record.favorite}`, `personal_rating: ${record.personalRating ?? ""}`, `last_watched: ${JSON.stringify(record.lastWatched)}`, "family:", `  decision: ${family.decision}`, `  min_age: ${JSON.stringify(family.minAge)}`, `  violence: ${family.violence}`, `  sexual_content: ${family.sexualContent}`, `  language: ${family.language}`, `  substances: ${family.substances}`, `  themes: ${family.themes}`, `  notes: ${JSON.stringify(family.notes)}`, `  prompts: ${JSON.stringify(family.prompts)}`, `created: ${record.created}`, `updated: ${record.updated}`, "---"].join("\n"); const details = [DETAIL_START, `## ${record.title}`, "", `- Type: ${record.mediaType === "movie" ? "Movie" : "Series"}`, `- Year: ${record.year || "—"}`, `- Runtime: ${record.runtime ? `${record.runtime} min` : "—"}`, `- Genres: ${record.genres.join(", ") || "—"}`, `- Family decision: ${FAMILY_DECISIONS[family.decision]}`, `- Suggested minimum age: ${family.minAge || "—"}`, "", "## Family guide", "", `- Violence and intensity: ${CONCERN_LEVELS[family.violence]}`, `- Sexual content and nudity: ${CONCERN_LEVELS[family.sexualContent]}`, `- Language: ${CONCERN_LEVELS[family.language]}`, `- Substances: ${CONCERN_LEVELS[family.substances]}`, `- Themes: ${CONCERN_LEVELS[family.themes]}`, family.notes ? `\n### Family notes\n\n${family.notes}` : "", family.prompts ? `\n### Discussion prompts\n\n${family.prompts}` : "", DETAIL_END].filter(Boolean).join("\n"); return `${yaml}\n\n${details}\n\n## Personal notes\n\n${personalNotes}\n`; }
  private async syncListTags(file: TFile, lists: string[]): Promise<void> { await this.app.fileManager.processFrontMatter(file, frontmatter => { const otherTags = list(frontmatter.tags).filter(tag => !tag.toLocaleLowerCase().startsWith(LIST_TAG_PREFIX)); frontmatter.tags = unique([...otherTags, ...unique(lists).map(listTag)]); }); }
  async save(input: MediaRecord, existing?: MediaRecord): Promise<MediaRecord> { await this.initialize(); const duplicate = this.duplicate(input, existing?.path ?? ""); if (duplicate) throw new Error(`This title already exists: ${duplicate.title}.`); const record = { ...input, lists: unique(input.lists), id: existing?.id || input.id || id(), created: existing?.created || input.created || now(), updated: now(), path: existing?.path ?? "" }; if (existing) { const file = this.app.vault.getAbstractFileByPath(existing.path); if (!(file instanceof TFile)) throw new Error("The existing media note could not be found."); const current = await this.app.vault.read(file); await this.app.vault.process(file, () => this.render(record, this.personalNotes(current))); await this.syncListTags(file, record.lists); return record; } let path = normalizePath(`${this.mediaRoot}/${safe(record.title)}${record.year ? ` (${record.year})` : ""}.md`); let suffix = 2; while (this.app.vault.getAbstractFileByPath(path)) path = normalizePath(`${this.mediaRoot}/${safe(record.title)}${record.year ? ` (${record.year})` : ""} ${suffix++}.md`); const file = await this.app.vault.create(path, this.render(record, "")); await this.syncListTags(file, record.lists); return { ...record, path: file.path }; }
  async update(record: MediaRecord, patch: Partial<MediaRecord>): Promise<MediaRecord> { return this.save({ ...record, ...patch, family: patch.family ?? record.family }, record); }
  async openIndex(): Promise<TFile> { await this.initialize(); const path = normalizePath(`${this.root}/Movie Library Index.md`); const existing = this.app.vault.getAbstractFileByPath(path); const file = existing instanceof TFile ? existing : await this.app.vault.create(path, "---\ntype: movie-library-index\ncreated: " + now() + "\n---\n\n# Movie Library\n\n" + INDEX_START + "\nIndex will be generated by Movie Library.\n" + INDEX_END + "\n\n## Personal notes\n\n"); await this.rebuildIndex(file); return file; }
  async rebuild(): Promise<void> { const index = this.app.vault.getAbstractFileByPath(normalizePath(`${this.root}/Movie Library Index.md`)); if (index instanceof TFile) await this.rebuildIndex(index); }
  private async rebuildIndex(file: TFile): Promise<void> { const records = this.records(); const genres = this.genreCounts(records).slice(0, 10).map(([genre, count]) => `- ${genre}: ${count}`); const body = ["## Overview", "", `- Total media: ${records.length}`, `- Movies: ${records.filter(record => record.mediaType === "movie").length}`, `- Series: ${records.filter(record => record.mediaType === "series").length}`, `- Watched: ${records.filter(record => record.watched).length}`, `- Watchlist: ${records.filter(record => record.watchlist).length}`, "", "## Top genres", "", ...(genres.length ? genres : ["No genres recorded yet."])].join("\n"); const current = await this.app.vault.read(file); const replacement = `${INDEX_START}\n${body}\n${INDEX_END}`; const expression = new RegExp(`${INDEX_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${INDEX_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`); const next = expression.test(current) ? current.replace(expression, replacement) : `${current.trim()}\n\n${replacement}\n`; if (next !== current) await this.app.vault.process(file, () => next); }
  async upsertPlex(input: MediaRecord): Promise<"created" | "updated"> { const existing = this.duplicate(input); if (!existing) { await this.save(input); return "created"; } await this.update(existing, { title: input.title, mediaType: input.mediaType, year: input.year || existing.year, runtime: input.runtime ?? existing.runtime, genres: input.genres.length ? input.genres : existing.genres, director: input.director || existing.director, cast: input.cast.length ? input.cast : existing.cast, imdbId: input.imdbId || existing.imdbId, contentRating: input.contentRating || existing.contentRating, plot: input.plot || existing.plot, plexThumbPath: input.plexThumbPath, plexRatingKey: input.plexRatingKey, watched: input.watched, lastWatched: input.lastWatched, personalRating: input.personalRating ?? existing.personalRating }); return "updated"; }
  genreCounts(records = this.records()): [string, number][] { const counts = new Map<string, number>(); records.forEach(record => record.genres.forEach(genre => counts.set(genre, (counts.get(genre) ?? 0) + 1))); return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])); }
}

class MediaModal extends Modal {
  private value: MediaRecord;
  constructor(app: App, private plugin: MovieLibraryPlugin, existing?: MediaRecord, imported?: Partial<MediaRecord>) { super(app); this.value = existing ? { ...existing, genres: [...existing.genres], cast: [...existing.cast], lists: [...existing.lists], family: { ...existing.family } } : { id: "", title: "", mediaType: "movie", year: "", runtime: null, genres: [], director: "", cast: [], imdbId: "", contentRating: "", plot: "", posterUrl: "", plexThumbPath: "", plexRatingKey: "", lists: [], watched: false, watchlist: true, owned: false, favorite: false, personalRating: null, lastWatched: "", created: "", updated: "", path: "", ...imported, family: { ...defaultFamily(plugin.settings), ...(imported?.family ?? {}) } }; }
  onOpen(): void { this.modalEl.addClass("movie-library-modal"); this.setTitle(this.value.path ? "Edit media" : "Add media"); this.render(); }
  private render(): void { const root = this.contentEl; root.empty(); const intro = root.createEl("p", { text: "Everything here is saved in an ordinary Markdown note. Fields marked as family guidance are your own household decisions." }); const grid = root.createDiv({ cls: "movie-library-form-grid" }); const text = (label: string, value: () => string, save: (next: string) => void, placeholder = ""): void => { const box = grid.createDiv({ cls: "movie-library-field" }); box.createEl("label", { text: label }); const input = box.createEl("input", { type: "text", attr: { placeholder } }); input.value = value(); input.addEventListener("input", () => save(input.value)); };
    text("Title", () => this.value.title, value => this.value.title = value, "Title"); text("Year", () => this.value.year, value => this.value.year = value, "2026"); const typeBox = grid.createDiv({ cls: "movie-library-field" }); typeBox.createEl("label", { text: "Type" }); const type = typeBox.createEl("select"); type.createEl("option", { value: "movie", text: "Movie" }); type.createEl("option", { value: "series", text: "Series" }); type.value = this.value.mediaType; type.addEventListener("change", () => this.value.mediaType = type.value as MediaType); text("Runtime (minutes)", () => this.value.runtime ? String(this.value.runtime) : "", value => this.value.runtime = number(value), "120"); text("Genres", () => this.value.genres.join(", "), value => this.value.genres = unique(value.split(",")), "Drama, Action"); text("Director", () => this.value.director, value => this.value.director = value); text("Cast", () => this.value.cast.join(", "), value => this.value.cast = unique(value.split(","))); text("IMDb ID", () => this.value.imdbId, value => this.value.imdbId = value, "tt1234567"); text("Content rating", () => this.value.contentRating, value => this.value.contentRating = value, "PG-13"); text("Poster URL", () => this.value.posterUrl, value => this.value.posterUrl = value, "https://...");
    const lists = grid.createDiv({ cls: "movie-library-field movie-library-wide" }); lists.createEl("label", { text: "Custom lists" }); const listInput = lists.createEl("input", { type: "text", attr: { placeholder: "Family favorites, Date night" } }); listInput.value = this.value.lists.join(", "); listInput.addEventListener("input", () => this.value.lists = unique(listInput.value.split(","))); const known = unique(this.plugin.repository.records().flatMap(record => record.lists)); if (known.length) lists.createEl("small", { text: `Existing lists: ${known.join(", ")}`, cls: "movie-library-muted" });
    const plot = grid.createDiv({ cls: "movie-library-field movie-library-wide" }); plot.createEl("label", { text: "Plot" }); const plotInput = plot.createEl("textarea"); plotInput.rows = 3; plotInput.value = this.value.plot; plotInput.addEventListener("input", () => this.value.plot = plotInput.value);
    const tracking = root.createDiv({ cls: "movie-library-form-section" }); tracking.createEl("h3", { text: "Personal tracking" }); const toggles = tracking.createDiv({ cls: "movie-library-toggle-grid" }); ([ ["Watched", "watched"], ["Watchlist", "watchlist"], ["Owned", "owned"], ["Favorite", "favorite"] ] as [string, keyof Pick<MediaRecord, "watched" | "watchlist" | "owned" | "favorite">][]).forEach(([label, key]) => { const line = toggles.createEl("label"); const check = line.createEl("input", { type: "checkbox" }); check.checked = this.value[key]; check.addEventListener("change", () => this.value[key] = check.checked); line.createSpan({ text: label }); }); const rating = toggles.createDiv({ cls: "movie-library-field" }); rating.createEl("label", { text: "Personal rating (1–10)" }); const ratingInput = rating.createEl("input", { type: "number", attr: { min: "1", max: "10", step: "0.5" } }); ratingInput.value = this.value.personalRating ? String(this.value.personalRating) : ""; ratingInput.addEventListener("input", () => this.value.personalRating = number(ratingInput.value)); const watchedDate = toggles.createDiv({ cls: "movie-library-field" }); watchedDate.createEl("label", { text: "Last watched" }); const watchedInput = watchedDate.createEl("input", { type: "date" }); watchedInput.value = this.value.lastWatched; watchedInput.addEventListener("change", () => this.value.lastWatched = watchedInput.value);
    const family = root.createDiv({ cls: "movie-library-form-section" }); family.createEl("h3", { text: "Family guide" }); const familyGrid = family.createDiv({ cls: "movie-library-form-grid" }); const select = (parent: HTMLElement, label: string, values: Record<string, string>, current: string, save: (next: string) => void): void => { const box = parent.createDiv({ cls: "movie-library-field" }); box.createEl("label", { text: label }); const input = box.createEl("select"); Object.entries(values).forEach(([value, textValue]) => input.createEl("option", { value, text: textValue })); input.value = current; input.addEventListener("change", () => save(input.value)); };
    select(familyGrid, "Overall decision", FAMILY_DECISIONS, this.value.family.decision, value => this.value.family.decision = value as FamilyDecision); const minAge = familyGrid.createDiv({ cls: "movie-library-field" }); minAge.createEl("label", { text: "Suggested minimum age" }); const ageInput = minAge.createEl("input", { type: "text", attr: { placeholder: "13+" } }); ageInput.value = this.value.family.minAge; ageInput.addEventListener("input", () => this.value.family.minAge = ageInput.value); ([ ["Violence and intensity", "violence"], ["Sexual content and nudity", "sexualContent"], ["Language", "language"], ["Substances", "substances"], ["Themes", "themes"] ] as [string, keyof Pick<FamilyGuide, "violence" | "sexualContent" | "language" | "substances" | "themes">][]).forEach(([label, key]) => select(familyGrid, label, CONCERN_LEVELS, this.value.family[key], value => this.value.family[key] = value as ConcernLevel)); const familyNotes = familyGrid.createDiv({ cls: "movie-library-field movie-library-wide" }); familyNotes.createEl("label", { text: "Family notes" }); const noteInput = familyNotes.createEl("textarea"); noteInput.rows = 3; noteInput.value = this.value.family.notes; noteInput.addEventListener("input", () => this.value.family.notes = noteInput.value); const prompts = familyGrid.createDiv({ cls: "movie-library-field movie-library-wide" }); prompts.createEl("label", { text: "Discussion prompts" }); const promptInput = prompts.createEl("textarea"); promptInput.rows = 2; promptInput.value = this.value.family.prompts; promptInput.addEventListener("input", () => this.value.family.prompts = promptInput.value);
    const actions = root.createDiv({ cls: "movie-library-actions" }); const save = actions.createEl("button", { text: this.value.path ? "Save changes" : "Save media", cls: "mod-cta" }); save.onclick = async () => { if (!this.value.title.trim()) { new Notice("A title is required."); return; } save.disabled = true; try { const saved = await this.plugin.repository.save({ ...this.value, title: this.value.title.trim(), genres: unique(this.value.genres), cast: unique(this.value.cast), watched: this.value.watched, lastWatched: this.value.watched && !this.value.lastWatched ? dateToday() : this.value.lastWatched }, this.value.path ? this.value : undefined); this.close(); new Notice(`${saved.title} saved.`); await this.plugin.refreshDashboard(); } catch (error) { new Notice(error instanceof Error ? error.message : "Could not save media."); save.disabled = false; } }; if (this.value.imdbId) { const guide = actions.createEl("button", { text: "Research parental guide" }); guide.onclick = () => window.open(`https://www.imdb.com/title/${encodeURIComponent(this.value.imdbId)}/parentalguide/`, "_blank"); }
    intro.addClass("movie-library-muted"); }
}

class LookupModal extends Modal {
  private query = ""; private results: OmdbResult[] = [];
  constructor(app: App, private plugin: MovieLibraryPlugin) { super(app); }
  onOpen(): void { this.modalEl.addClass("movie-library-modal"); this.setTitle("Look up movie or series"); this.render(); }
  private render(): void { this.contentEl.empty(); if (!this.plugin.settings.omdbKey) { this.contentEl.createEl("p", { text: "OMDb lookup is optional. Add a free OMDb key in Movie Library settings, or use Manual entry instead." }); const manual = this.contentEl.createEl("button", { text: "Manual entry", cls: "mod-cta" }); manual.onclick = () => { this.close(); new MediaModal(this.app, this.plugin).open(); }; return; } const line = this.contentEl.createDiv({ cls: "movie-library-lookup" }); const input = line.createEl("input", { type: "text", attr: { placeholder: "Title or IMDb ID" } }); input.value = this.query; input.addEventListener("input", () => this.query = input.value); const search = line.createEl("button", { text: "Search", cls: "mod-cta" }); const go = async (): Promise<void> => { if (!this.query.trim()) return; search.disabled = true; search.textContent = "Searching…"; try { this.results = await this.plugin.searchOmdb(this.query.trim()); this.render(); } catch (error) { new Notice(error instanceof Error ? error.message : "Lookup failed."); search.disabled = false; search.textContent = "Search"; } }; search.onclick = () => void go(); input.addEventListener("keydown", event => { if (event.key === "Enter") void go(); }); const results = this.contentEl.createDiv({ cls: "movie-library-lookup-results" }); for (const result of this.results) { const item = results.createEl("button", { cls: "movie-library-lookup-result" }); this.poster(item, result.Poster, result.Title ?? ""); const copy = item.createDiv(); copy.createEl("strong", { text: result.Title ?? "Untitled" }); copy.createEl("small", { text: `${result.Year ?? "—"} · ${result.Type === "series" ? "Series" : "Movie"}` }); item.onclick = async () => { try { const details = result.imdbID ? await this.plugin.omdbDetails(result.imdbID) : result; this.close(); new MediaModal(this.app, this.plugin, undefined, this.plugin.fromOmdb(details)).open(); } catch (error) { new Notice(error instanceof Error ? error.message : "Could not open this result."); } }; } }
  private poster(parent: HTMLElement, url: string | undefined, title: string): void { if (!url || url === "N/A") { parent.createDiv({ cls: "movie-library-poster-placeholder", text: "No artwork" }); return; } const image = parent.createEl("img", { attr: { src: url, alt: `${title} poster` }, cls: "movie-library-lookup-poster" }); image.onerror = () => { image.remove(); parent.createDiv({ cls: "movie-library-poster-placeholder", text: "No artwork" }); }; }
}

class PickerModal extends Modal {
  private type = "all"; private genre = "all"; private maxRuntime = ""; private minRating = ""; private family = "all";
  constructor(app: App, private plugin: MovieLibraryPlugin) { super(app); }
  onOpen(): void { this.modalEl.addClass("movie-library-modal"); this.setTitle("What should we watch?"); this.render(); }
  private render(): void { this.contentEl.empty(); const records = this.plugin.repository.records(); const controls = this.contentEl.createDiv({ cls: "movie-library-picker-controls" }); const select = (label: string, options: [string, string][], current: string, change: (value: string) => void): void => { const field = controls.createDiv({ cls: "movie-library-field" }); field.createEl("label", { text: label }); const input = field.createEl("select"); options.forEach(([value, text]) => input.createEl("option", { value, text })); input.value = current; input.addEventListener("change", () => { change(input.value); this.render(); }); };
    select("Type", [["all", "Movies and series"], ["movie", "Movies"], ["series", "Series"]], this.type, value => this.type = value); select("Genre", [["all", "All genres"], ...this.plugin.repository.genreCounts(records).map(([genre]) => [genre, genre] as [string, string])], this.genre, value => this.genre = value); select("Maximum runtime", [["", "Any length"], ["90", "Up to 90 min"], ["120", "Up to 2 hours"], ["150", "Up to 2½ hours"]], this.maxRuntime, value => this.maxRuntime = value); select("Minimum rating", [["", "Any rating"], ["6", "6+"], ["7", "7+"], ["8", "8+"]], this.minRating, value => this.minRating = value); select("Family decision", [["all", "Any decision"], ...Object.entries(FAMILY_DECISIONS).map(([value, text]) => [value, text] as [string, string])], this.family, value => this.family = value);
    const matches = records.filter(record => !record.watched && (this.type === "all" || record.mediaType === this.type) && (this.genre === "all" || record.genres.some(genre => normalize(genre) === normalize(this.genre))) && (!this.maxRuntime || !record.runtime || record.runtime <= Number(this.maxRuntime)) && (!this.minRating || (record.personalRating ?? 0) >= Number(this.minRating)) && (this.family === "all" || record.family.decision === this.family)); const watchlist = matches.filter(record => record.watchlist); const pool = this.plugin.settings.pickerWatchlistFirst && watchlist.length ? watchlist : matches; const displayed = [...pool].sort(() => Math.random() - .5).slice(0, 6); const results = this.contentEl.createDiv({ cls: "movie-library-picker-results" }); if (!displayed.length) results.createEl("p", { text: "No unwatched titles match these filters.", cls: "movie-library-muted" }); displayed.forEach(record => this.plugin.renderCard(results, record, () => this.close())); const random = this.contentEl.createEl("button", { text: "Randomize", cls: "mod-cta" }); random.onclick = () => this.render(); }
}

class RatingModal extends Modal {
  private rating: string; private watched: string;
  constructor(app: App, private plugin: MovieLibraryPlugin, private record: MediaRecord) { super(app); this.rating = record.personalRating ? String(record.personalRating) : ""; this.watched = record.lastWatched; }
  onOpen(): void { this.modalEl.addClass("movie-library-modal"); this.setTitle(`Update ${this.record.title}`); new Setting(this.contentEl).setName("Personal rating").setDesc("Use 1–10; leave blank to clear.").addText(input => { input.inputEl.type = "number"; input.inputEl.min = "1"; input.inputEl.max = "10"; input.inputEl.step = "0.5"; input.setValue(this.rating).onChange(value => this.rating = value); }); new Setting(this.contentEl).setName("Last watched").addText(input => { input.inputEl.type = "date"; input.setValue(this.watched).onChange(value => this.watched = value); }); new Setting(this.contentEl).addButton(button => button.setButtonText("Save").setCta().onClick(async () => { await this.plugin.repository.update(this.record, { personalRating: number(this.rating), lastWatched: this.watched }); this.close(); await this.plugin.refreshDashboard(); })); }
}

class MovieLibraryDashboard extends ItemView {
  private query = ""; private type = "all"; private genre = "all"; private state = "all"; private family = "all"; private year = ""; private minRating = ""; private maxRuntime = "";
  constructor(leaf: WorkspaceLeaf, private plugin: MovieLibraryPlugin) { super(leaf); }
  getViewType(): string { return VIEW; } getDisplayText(): string { return "Movie Library"; } getIcon(): string { return "film"; }
  async onOpen(): Promise<void> { await this.render(); }
  async render(): Promise<void> { const root = this.containerEl.children[1] as HTMLElement; root.empty(); root.addClass("movie-library-dashboard", `movie-library-density-${this.plugin.settings.galleryDensity}`); const records = this.plugin.repository.records(); const hero = root.createDiv({ cls: "movie-library-hero" }); hero.createEl("div", { text: "PERSONAL MEDIA LIBRARY", cls: "movie-library-eyebrow" }); hero.createEl("h1", { text: "Movie Library" }); hero.createEl("p", { text: records.length ? "Browse your collection, make a wise selection, and keep the household guide close at hand." : "Add your first movie or series to start a private Markdown-first media library." }); const actions = hero.createDiv({ cls: "movie-library-actions" }); this.button(actions, "Look up media", () => new LookupModal(this.app, this.plugin).open(), true); this.button(actions, "Manual entry", () => new MediaModal(this.app, this.plugin).open()); this.button(actions, "What should we watch?", () => new PickerModal(this.app, this.plugin).open()); this.button(actions, "Open index", () => void this.plugin.openIndex()); this.button(actions, "Refresh", () => void this.plugin.rebuild()); this.button(actions, "Settings", () => this.plugin.openSettings());
    const metrics = root.createDiv({ cls: "movie-library-metrics" }); this.metric(metrics, String(records.length), "Total media"); this.metric(metrics, String(records.filter(record => record.mediaType === "movie").length), "Movies"); this.metric(metrics, String(records.filter(record => record.mediaType === "series").length), "Series"); this.metric(metrics, String(records.filter(record => record.watchlist && !record.watched).length), "Watchlist"); this.metric(metrics, String(records.filter(record => record.watched).length), "Watched"); this.metric(metrics, String(records.filter(record => record.favorite).length), "Favorites");
    if (!records.length) { root.createDiv({ cls: "movie-library-empty", text: "The new Movie Library root is empty. Existing media notes elsewhere in the vault remain separate and unchanged." }); return; }
    const dashboardGrid = root.createDiv({ cls: "movie-library-widgets" }); this.widget(dashboardGrid, "Watchlist picks", records.filter(record => record.watchlist && !record.watched).slice(0, 4)); this.widget(dashboardGrid, "Favorites", records.filter(record => record.favorite).slice(0, 4)); this.widget(dashboardGrid, "Recent additions", [...records].sort((a, b) => b.created.localeCompare(a.created)).slice(0, 4)); this.widget(dashboardGrid, "Recent watches", records.filter(record => record.lastWatched).sort((a, b) => b.lastWatched.localeCompare(a.lastWatched)).slice(0, 4)); const genres = dashboardGrid.createDiv({ cls: "movie-library-widget" }); genres.createEl("h2", { text: "Top genres" }); this.plugin.repository.genreCounts(records).slice(0, 7).forEach(([genre, count]) => { const row = genres.createDiv({ cls: "movie-library-genre-row" }); row.createSpan({ text: genre }); row.createEl("strong", { text: String(count) }); }); const ratings = dashboardGrid.createDiv({ cls: "movie-library-widget" }); ratings.createEl("h2", { text: "Rating distribution" }); [9, 8, 7, 6].forEach(minimum => { const count = records.filter(record => (record.personalRating ?? 0) >= minimum).length; const row = ratings.createDiv({ cls: "movie-library-genre-row" }); row.createSpan({ text: `${minimum}+ stars` }); row.createEl("strong", { text: String(count) }); });
    const filters = root.createDiv({ cls: "movie-library-filters" }); const search = filters.createEl("input", { type: "search", attr: { placeholder: "Search title, genre, director, cast…" } }); search.value = this.query; search.addEventListener("input", () => { this.query = search.value; this.render(); }); const select = (options: [string, string][], current: string, change: (value: string) => void): void => { const control = filters.createEl("select"); options.forEach(([value, text]) => control.createEl("option", { value, text })); control.value = current; control.addEventListener("change", () => { change(control.value); this.render(); }); }; const numberFilter = (placeholder: string, current: string, change: (value: string) => void): void => { const input = filters.createEl("input", { type: "number", attr: { placeholder, min: "0" } }); input.value = current; input.addEventListener("change", () => { change(input.value); this.render(); }); }; select([["all", "All types"], ["movie", "Movies"], ["series", "Series"]], this.type, value => this.type = value); select([["all", "All genres"], ...this.plugin.repository.genreCounts(records).map(([genre]) => [genre, genre] as [string, string])], this.genre, value => this.genre = value); select([["all", "All states"], ["watchlist", "Watchlist"], ["watched", "Watched"], ["owned", "Owned"], ["favorite", "Favorites"]], this.state, value => this.state = value); select([["all", "All family decisions"], ...Object.entries(FAMILY_DECISIONS).map(([value, text]) => [value, text] as [string, string])], this.family, value => this.family = value); numberFilter("Year", this.year, value => this.year = value); numberFilter("Minimum rating", this.minRating, value => this.minRating = value); numberFilter("Max runtime", this.maxRuntime, value => this.maxRuntime = value);
    const matching = records.filter(record => (!this.query || [record.title, record.year, record.director, ...record.cast, ...record.genres].join(" ").toLocaleLowerCase().includes(this.query.toLocaleLowerCase())) && (this.type === "all" || record.mediaType === this.type) && (this.genre === "all" || record.genres.some(genre => normalize(genre) === normalize(this.genre))) && (this.family === "all" || record.family.decision === this.family) && (!this.year || record.year === this.year) && (!this.minRating || (record.personalRating ?? 0) >= Number(this.minRating)) && (!this.maxRuntime || !record.runtime || record.runtime <= Number(this.maxRuntime)) && (this.state === "all" || (this.state === "watchlist" && record.watchlist) || (this.state === "watched" && record.watched) || (this.state === "owned" && record.owned) || (this.state === "favorite" && record.favorite))); const heading = root.createEl("h2", { text: `${matching.length} matching title${matching.length === 1 ? "" : "s"}`, cls: "movie-library-gallery-heading" }); heading.setAttr("aria-live", "polite"); const gallery = root.createDiv({ cls: "movie-library-gallery" }); matching.forEach(record => this.plugin.renderCard(gallery, record)); }
  private widget(parent: HTMLElement, title: string, records: MediaRecord[]): void { const widget = parent.createDiv({ cls: "movie-library-widget" }); widget.createEl("h2", { text: title }); if (!records.length) widget.createEl("p", { text: "Nothing here yet.", cls: "movie-library-muted" }); records.forEach(record => { const item = widget.createDiv({ cls: "movie-library-widget-item" }); item.createEl("strong", { text: record.title }); item.createEl("small", { text: `${record.year || "—"} · ${record.mediaType}` }); }); }
  private button(parent: HTMLElement, label: string, action: () => void, primary = false): void { parent.createEl("button", { text: label, cls: primary ? "mod-cta" : "" }).onclick = action; }
  private metric(parent: HTMLElement, value: string, label: string): void { const box = parent.createDiv({ cls: "movie-library-metric" }); box.createEl("strong", { text: value }); box.createEl("span", { text: label }); }
}

class PlexLibrariesModal extends Modal {
  constructor(app: App, private plugin: MovieLibraryPlugin) { super(app); }
  async onOpen(): Promise<void> { this.setTitle("Choose Plex libraries"); try { const libraries = await this.plugin.plexLibraries(); if (!libraries.length) { this.contentEl.createEl("p", { text: "No movie or series libraries were found." }); return; } const selected = new Set(this.plugin.settings.plexLibraryKeys); this.contentEl.createEl("p", { text: "Leave every item unchecked to sync all movie and series libraries." }); libraries.forEach(library => { new Setting(this.contentEl).setName(library.title).setDesc(`${library.type === "show" ? "Series" : "Movies"} · Plex library ${library.key}`).addToggle(toggle => toggle.setValue(selected.has(library.key)).onChange(value => value ? selected.add(library.key) : selected.delete(library.key))); }); new Setting(this.contentEl).addButton(button => button.setButtonText("Save selection").setCta().onClick(async () => { this.plugin.settings.plexLibraryKeys = [...selected]; await this.plugin.saveSettings(); this.close(); new Notice(selected.size ? "Plex library selection saved." : "All Plex movie and series libraries will be synced."); })); } catch (error) { this.contentEl.createEl("p", { text: error instanceof Error ? error.message : "Could not connect to Plex." }); }
  }
}

class MovieLibrarySettings extends PluginSettingTab {
  constructor(app: App, private plugin: MovieLibraryPlugin) { super(app, plugin); }
  display(): void { const { containerEl } = this; containerEl.empty(); containerEl.createEl("h2", { text: "Movie Library" });
    new Setting(containerEl).setName("Library root folder").setDesc("All new Movie Library Markdown notes stay beneath this one root.").addText(text => text.setValue(this.plugin.settings.rootFolder).onChange(async value => { this.plugin.settings.rootFolder = value.trim().replace(/^\/+|\/+$/g, "") || DEFAULT.rootFolder; await this.plugin.saveSettings(); }));
    new Setting(containerEl).setName("OMDb API key").setDesc("Optional. Enables metadata and artwork lookup; it is stored only in local plugin settings.").addText(text => { text.inputEl.type = "password"; text.setValue(this.plugin.settings.omdbKey).onChange(async value => { this.plugin.settings.omdbKey = value.trim(); await this.plugin.saveSettings(); }); }).addButton(button => button.setButtonText("Test connection").onClick(async () => { try { await this.plugin.testOmdb(); new Notice("OMDb connection succeeded."); } catch (error) { new Notice(error instanceof Error ? error.message : "Could not connect to OMDb."); } }));
    containerEl.createEl("h3", { text: "Optional Plex sync" });
    new Setting(containerEl).setName("Plex server URL").setDesc("For mobile, use a LAN address reachable by your phone, not localhost (for example, http://192.168.x.x:32400). ").addText(text => text.setPlaceholder("http://192.168.1.10:32400").setValue(this.plugin.settings.plexServerUrl).onChange(async value => { this.plugin.settings.plexServerUrl = value.trim().replace(/\/+$/, ""); await this.plugin.saveSettings(); }));
    new Setting(containerEl).setName("Plex token").setDesc("Stored only in local Obsidian settings; never written to Markdown notes.").addText(text => { text.inputEl.type = "password"; text.setValue(this.plugin.settings.plexToken).onChange(async value => { this.plugin.settings.plexToken = value.trim(); await this.plugin.saveSettings(); }); }).addButton(button => button.setButtonText("Test Plex").onClick(async () => { try { const libraries = await this.plugin.plexLibraries(); new Notice(`Plex connected: ${libraries.length} movie or series libraries found.`); } catch (error) { new Notice(error instanceof Error ? error.message : "Could not connect to Plex."); } }));
    new Setting(containerEl).setName("Plex libraries").setDesc(this.plugin.settings.plexLibraryKeys.length ? `Selected: ${this.plugin.settings.plexLibraryKeys.join(", ")}` : "All movie and series libraries will be imported. Choose libraries to narrow the sync.").addButton(button => button.setButtonText("Choose libraries").onClick(() => new PlexLibrariesModal(this.app, this.plugin).open())).addButton(button => button.setButtonText("Sync now").setCta().onClick(async () => { try { await this.plugin.importPlex(); } catch (error) { new Notice(error instanceof Error ? error.message : "Plex sync failed."); } }));
    new Setting(containerEl).setName("Gallery density").addDropdown(dropdown => dropdown.addOptions({ compact: "Compact", comfortable: "Comfortable", large: "Large" }).setValue(this.plugin.settings.galleryDensity).onChange(async value => { this.plugin.settings.galleryDensity = value as GalleryDensity; await this.plugin.saveSettings(); })); new Setting(containerEl).setName("Prioritize watchlist in picker").addToggle(toggle => toggle.setValue(this.plugin.settings.pickerWatchlistFirst).onChange(async value => { this.plugin.settings.pickerWatchlistFirst = value; await this.plugin.saveSettings(); })); new Setting(containerEl).setName("Default family decision").addDropdown(dropdown => dropdown.addOptions(FAMILY_DECISIONS).setValue(this.plugin.settings.defaultFamilyDecision).onChange(async value => { this.plugin.settings.defaultFamilyDecision = value as FamilyDecision; await this.plugin.saveSettings(); })); new Setting(containerEl).setName("Default suggested minimum age").addText(text => text.setPlaceholder("13+").setValue(this.plugin.settings.defaultMinAge).onChange(async value => { this.plugin.settings.defaultMinAge = value.trim(); await this.plugin.saveSettings(); })); containerEl.createEl("p", { text: "Plex sync is one-way and optional. It imports availability, watched state, Plex user ratings when present, dates, and artwork paths. Your local tracking, family guide, and notes are not overwritten." }); }
}

export default class MovieLibraryPlugin extends Plugin {
  settings: SettingsData = DEFAULT; repository!: MovieRepository;
  async onload(): Promise<void> { this.settings = Object.assign({}, DEFAULT, await this.loadData() as Partial<SettingsData> | null); if (!Array.isArray(this.settings.plexLibraryKeys)) this.settings.plexLibraryKeys = []; this.repository = new MovieRepository(this.app, this.settings); this.registerView(VIEW, leaf => new MovieLibraryDashboard(leaf, this)); this.addSettingTab(new MovieLibrarySettings(this.app, this)); this.addRibbonIcon("film", "Open Movie Library", () => void this.openDashboard()); this.addCommand({ id: "open-dashboard", name: "Open dashboard", callback: () => void this.openDashboard() }); this.addCommand({ id: "sync-plex", name: "Sync from Plex", callback: () => void this.importPlex() }); this.addCommand({ id: "lookup-media", name: "Look up movie or series", callback: () => new LookupModal(this.app, this).open() }); this.addCommand({ id: "manual-entry", name: "Add media manually", callback: () => new MediaModal(this.app, this).open() }); this.addCommand({ id: "watch-picker", name: "What should we watch?", callback: () => new PickerModal(this.app, this).open() }); this.addCommand({ id: "open-index", name: "Open Movie Library Index", callback: () => void this.openIndex() }); this.addCommand({ id: "refresh", name: "Refresh Movie Library", callback: () => void this.rebuild() }); }
  async saveSettings(): Promise<void> { await this.saveData(this.settings); this.repository.configure(this.settings); await this.refreshDashboard(); }
  async openDashboard(): Promise<void> { await this.repository.initialize(); await this.repository.rebuild(); let leaf = this.app.workspace.getLeavesOfType(VIEW)[0]; if (!leaf) { leaf = this.app.workspace.getLeaf("tab"); await leaf.setViewState({ type: VIEW, active: true }); } await this.app.workspace.revealLeaf(leaf); }
  async openIndex(): Promise<void> { const file = await this.repository.openIndex(); await this.openFile(file.path); }
  openSettings(): void { const settingsApp = this.app as App & { setting: { open(): void; openTabById(id: string): void } }; settingsApp.setting.open(); settingsApp.setting.openTabById(this.manifest.id); }
  async rebuild(): Promise<void> { await this.repository.rebuild(); new Notice("Movie Library refreshed."); await this.refreshDashboard(); }
  async openFile(path: string): Promise<void> { const file = this.app.vault.getAbstractFileByPath(path); if (file instanceof TFile) await this.app.workspace.getLeaf("tab").openFile(file); }
  async refreshDashboard(): Promise<void> { const view = this.app.workspace.getLeavesOfType(VIEW)[0]?.view; if (view instanceof MovieLibraryDashboard) await view.render(); }
  fromOmdb(result: OmdbResult): Partial<MediaRecord> { return { title: result.Title ?? "", mediaType: result.Type === "series" ? "series" : "movie", year: result.Year ?? "", runtime: parseRuntime(result.Runtime ?? ""), genres: unique((result.Genre ?? "").split(",")), director: result.Director === "N/A" ? "" : result.Director ?? "", cast: unique((result.Actors ?? "").split(",")), imdbId: result.imdbID ?? "", contentRating: result.Rated === "N/A" ? "" : result.Rated ?? "", plot: result.Plot === "N/A" ? "" : result.Plot ?? "", posterUrl: result.Poster === "N/A" ? "" : result.Poster ?? "" }; }
  async searchOmdb(query: string): Promise<OmdbResult[]> { if (!this.settings.omdbKey) throw new Error("Add an OMDb API key in Movie Library settings first."); if (/^tt\d+$/i.test(query)) return [await this.omdbDetails(query)]; const response = await requestUrl({ url: `https://www.omdbapi.com/?apikey=${encodeURIComponent(this.settings.omdbKey)}&s=${encodeURIComponent(query)}`, method: "GET" }); const data = response.json as { Search?: OmdbResult[]; Error?: string; Response?: string }; if (!data.Search?.length) throw new Error(data.Error || "No matching titles found."); return data.Search.filter(result => result.Type === "movie" || result.Type === "series"); }
  async omdbDetails(imdbId: string): Promise<OmdbResult> { const response = await requestUrl({ url: `https://www.omdbapi.com/?apikey=${encodeURIComponent(this.settings.omdbKey)}&i=${encodeURIComponent(imdbId)}&plot=short`, method: "GET" }); const data = response.json as OmdbResult; if (data.Response === "False" || data.Error) throw new Error(data.Error || "No matching title found."); return data; }
  async testOmdb(): Promise<void> { if (!this.settings.omdbKey) throw new Error("Add an OMDb API key first."); await this.omdbDetails("tt0133093"); }
  private plexBase(): string { const base = this.settings.plexServerUrl.trim().replace(/\/+$/, ""); if (!base || !this.settings.plexToken.trim()) throw new Error("Add both a Plex server URL and Plex token in Movie Library settings first."); if (!/^https?:\/\//i.test(base)) throw new Error("Plex server URL must begin with http:// or https://."); return base; }
  private async plexRequest(path: string): Promise<Record<string, unknown>> { const response = await requestUrl({ url: `${this.plexBase()}${path}`, method: "GET", headers: { Accept: "application/json", "X-Plex-Token": this.settings.plexToken.trim() } }); return response.json as Record<string, unknown>; }
  async plexLibraries(): Promise<PlexLibrary[]> { const data = await this.plexRequest("/library/sections"); const container = data.MediaContainer as { Directory?: Array<{ key?: string | number; title?: string; type?: string }> } | undefined; return (container?.Directory ?? []).filter(item => item.type === "movie" || item.type === "show").map(item => ({ key: String(item.key ?? ""), title: String(item.title ?? "Untitled library"), type: String(item.type ?? "") })).filter(item => item.key); }
  private fromPlex(item: PlexMetadata): MediaRecord | null { const title = String(item.title ?? "").trim(); if (!title) return null; const imdb = (item.Guid ?? []).map(guid => String(guid.id ?? "")).find(guid => /^imdb:\/\/tt\d+$/i.test(guid))?.replace(/^imdb:\/\//i, "") ?? ""; const seenAt = Number(item.lastViewedAt); const lastWatched = Number.isFinite(seenAt) && seenAt > 0 ? new Date(seenAt * 1000).toISOString().slice(0, 10) : ""; return { id: "", title, mediaType: item.type === "show" ? "series" : "movie", year: String(item.year ?? ""), runtime: item.duration ? Math.round(Number(item.duration) / 60000) : null, genres: unique((item.Genre ?? []).map(entry => String(entry.tag ?? ""))), director: unique((item.Director ?? []).map(entry => String(entry.tag ?? ""))).join(", "), cast: unique((item.Role ?? []).map(entry => String(entry.tag ?? ""))), imdbId: imdb, contentRating: String(item.contentRating ?? ""), plot: String(item.summary ?? ""), posterUrl: "", plexThumbPath: String(item.thumb ?? ""), plexRatingKey: String(item.ratingKey ?? ""), lists: [], watched: Number(item.viewCount ?? 0) > 0, watchlist: false, owned: false, favorite: false, personalRating: number(item.userRating), lastWatched, created: "", updated: "", family: defaultFamily(this.settings), path: "" }; }
  async importPlex(): Promise<void> { const libraries = await this.plexLibraries(); const selected = this.settings.plexLibraryKeys.length ? libraries.filter(library => this.settings.plexLibraryKeys.includes(library.key)) : libraries; if (!selected.length) throw new Error("No selected Plex movie or series libraries were found."); let created = 0; let updated = 0; let skipped = 0; for (const library of selected) { const data = await this.plexRequest(`/library/sections/${encodeURIComponent(library.key)}/all?X-Plex-Container-Start=0&X-Plex-Container-Size=5000`); const container = data.MediaContainer as { Metadata?: PlexMetadata[] } | undefined; for (const item of container?.Metadata ?? []) { const record = this.fromPlex(item); if (!record) { skipped++; continue; } const outcome = await this.repository.upsertPlex(record); outcome === "created" ? created++ : updated++; } } await this.repository.rebuild(); await this.refreshDashboard(); new Notice(`Plex sync complete: ${created} added, ${updated} updated${skipped ? `, ${skipped} skipped` : ""}.`); }
  plexPoster(record: MediaRecord): string { if (record.posterUrl) return record.posterUrl; if (!record.plexThumbPath || !this.settings.plexServerUrl || !this.settings.plexToken) return ""; return `${this.settings.plexServerUrl.replace(/\/+$/, "")}${record.plexThumbPath}${record.plexThumbPath.includes("?") ? "&" : "?"}X-Plex-Token=${encodeURIComponent(this.settings.plexToken)}`; }
  renderCard(parent: HTMLElement, record: MediaRecord, close?: () => void): void { const card = parent.createDiv({ cls: "movie-library-card" }); const poster = this.plexPoster(record); if (poster) { const image = card.createEl("img", { attr: { src: poster, alt: `${record.title} poster`, loading: "lazy" }, cls: "movie-library-poster" }); image.onerror = () => { image.remove(); card.createDiv({ cls: "movie-library-poster-placeholder", text: "No artwork" }); }; } else card.createDiv({ cls: "movie-library-poster-placeholder", text: "No artwork" }); const body = card.createDiv({ cls: "movie-library-card-body" }); body.createEl("strong", { text: record.title }); body.createEl("small", { text: `${record.year || "—"} · ${record.mediaType === "movie" ? "Movie" : "Series"}` }); const badges = body.createDiv({ cls: "movie-library-badges" }); if (record.watchlist && !record.watched) badges.createSpan({ text: "Watchlist", cls: "movie-library-badge" }); if (record.favorite) badges.createSpan({ text: "Favorite", cls: "movie-library-badge" }); if (record.owned) badges.createSpan({ text: "Owned", cls: "movie-library-badge" }); badges.createSpan({ text: FAMILY_DECISIONS[record.family.decision], cls: `movie-library-badge is-${record.family.decision}` }); if (record.personalRating) body.createEl("small", { text: `Your rating: ${record.personalRating}/10` }); const actions = body.createDiv({ cls: "movie-library-card-actions" }); const action = (label: string, run: () => Promise<void> | void): void => { const button = actions.createEl("button", { text: label }); button.onclick = () => void run(); }; action("Edit", () => new MediaModal(this.app, this, record).open()); action("Open", async () => { close?.(); await this.openFile(record.path); }); action(record.watched ? "Mark unwatched" : "Mark watched", async () => { await this.repository.update(record, { watched: !record.watched, lastWatched: record.watched ? "" : dateToday() }); await this.refreshDashboard(); }); action(record.watchlist ? "Remove list" : "Watchlist", async () => { await this.repository.update(record, { watchlist: !record.watchlist }); await this.refreshDashboard(); }); action(record.favorite ? "Unfavorite" : "Favorite", async () => { await this.repository.update(record, { favorite: !record.favorite }); await this.refreshDashboard(); }); action(record.owned ? "Unown" : "Owned", async () => { await this.repository.update(record, { owned: !record.owned }); await this.refreshDashboard(); }); action("Rate", () => new RatingModal(this.app, this, record).open()); if (record.imdbId) action("Guide", () => { window.open(`https://www.imdb.com/title/${encodeURIComponent(record.imdbId)}/parentalguide/`, "_blank"); }); }
}
